name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Display Go version
        run: go version

      - name: Get dependencies
        run: go mod download

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o b64-linux-amd64

      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -o b64-darwin-amd64

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o b64-windows-amd64.exe

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            b64-linux-amd64
            b64-darwin-amd64
            b64-windows-amd64.exe
